version: "3.7"
services:

  postgresql:
    image: postgres:12.0-alpine
    container_name: predico_enershare_postgresql
    restart: always
    env_file:
      - api/.env
    volumes:
      - postgresql-enershare-data:/var/lib/postgresql/data
    networks:
      - predico_network
    ports:
      - "5432:5432"

  app: &api
    build:
      context: api
      args:
        GITLAB_TOKEN: ${GITLAB_TOKEN}
    container_name: predico_enershare_rest_app
    environment:
      - WAIT_HOSTS=postgresql:5432
    restart: unless-stopped
    command: gunicorn -c gunicorn.conf api.wsgi:application -b :8000
    depends_on:
      - postgresql
    env_file:
      - api/.env
    networks:
      - predico_network
    volumes:
      - static_volume:/usr/src/django/api/staticfiles
      - media_volume:/usr/src/django/api/mediafiles

  nginx:
    container_name: predico_rest_nginx
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - predico_network
    volumes:
      - static_volume:/usr/src/api/staticfiles
      - media_volume:/usr/src/api/mediafiles
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  # Service for handling SSL certificates with Certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: /init_and_renew.sh
    volumes:
      - ./nginx/init_and_renew.sh:/init_and_renew.sh
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - default

volumes:
  postgresql-enershare-data:
  static_volume:
  media_volume:
  letsencrypt_data:
  certbot_www:

networks:
  predico_network:
    driver: bridge