version: "3.7"

services:
  postgresql:
    image: postgres:12.0-alpine
    container_name: predico_postgresql
    restart: always
    env_file:
      - api/.dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - predico_network

  app:
    build: api
    container_name: predico_rest_app
    environment:
      - WAIT_HOSTS=postgresql:5000
    restart: unless-stopped
    env_file:
      - api/.dev.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgresql
    ports:
      - "8081:8000"
    networks:
      - predico_network

volumes:
  postgresql-data:

networks:
  predico_network:
    driver: bridge