# Generated by Django 3.2 on 2021-12-18 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('forecasts', 'Forecast'), ('measurements', 'Measurement')], max_length=12)),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('units', models.CharField(choices=[('w', 'Watt'), ('kw', 'Kilo Watt'), ('mw', 'Mega Watt')], max_length=2)),
                ('time_interval', models.IntegerField(choices=[('5', 'T5'), ('15', 'T15'), ('30', 'T30'), ('60', 'T60')])),
                ('aggregation_type', models.CharField(choices=[('avg', 'Avg')], max_length=3)),
                ('registered_at', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userresources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raw_data',
                'unique_together': {('user', 'resource', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='MarketForecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('request', models.DateTimeField()),
                ('value', models.FloatField()),
                ('units', models.CharField(choices=[('w', 'Watt'), ('kw', 'Kilo Watt'), ('mw', 'Mega Watt')], max_length=2)),
                ('registered_at', models.DateTimeField()),
                ('market_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsession')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userresources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_forecasts',
                'unique_together': {('user', 'resource', 'market_session', 'datetime')},
            },
        ),
    ]
