# Generated by Django 5.0.3 on 2024-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='time_interval',
            field=models.IntegerField(choices=[(5, 'T5'), (15, 'T15'), (30, 'T30'), (60, 'T60')]),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='units',
            field=models.CharField(choices=[('w', 'Watt'), ('kw', 'Kilowatt'), ('mw', 'Megawatt')], max_length=2),
        ),
    ]
