# Generated by Django 3.2 on 2024-02-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransferOut',
            fields=[
                ('withdraw_transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('user_wallet_address', models.TextField()),
                ('tangle_msg_id', models.TextField()),
                ('is_solid', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'balance_transfer_out',
            },
        ),
    ]
