# Generated by Django 3.2 on 2023-01-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbalance',
            name='total_deposit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marketbalance',
            name='total_withdraw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marketsessionbalance',
            name='session_deposit',
            field=models.FloatField(default=0.0),
        ),
    ]
