# Generated by Django 5.0.3 on 2025-08-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancetransferout',
            old_name='tangle_msg_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='marketsessionbidpayment',
            old_name='tangle_msg_id',
            new_name='transaction_id',
        ),
    ]
